POST https://emoult.au.auth0.com/oauth/token HTTP/1.1
content-type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=r56tFyKXabWDKHwwPdcHzAZneE2jS5G6
&client_secret=fW__ptarmgF76j2SLOv0tQHuWk2dqL0wOZq02zILZOwEJqJaEZ8yvtDnS8keeLxw
&audience=https://logger.emoult.com
&scope=logger

###

GET http://localhost:3000/records HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InIyZ3dXbTVlTDdZc3lBQi1uWjl6RiJ9.eyJpc3MiOiJodHRwczovL2Vtb3VsdC5hdS5hdXRoMC5jb20vIiwic3ViIjoicjU2dEZ5S1hhYldES0h3d1BkY0h6QVpuZUUyalM1RzZAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vbG9nZ2VyLmVtb3VsdC5jb20iLCJpYXQiOjE1OTkxMDg0ODEsImV4cCI6MTU5OTE5NDg4MSwiYXpwIjoicjU2dEZ5S1hhYldES0h3d1BkY0h6QVpuZUUyalM1RzYiLCJzY29wZSI6ImxvZ2dlciByZWFkZXIgdXBkYXRlciBkZWxldGVyIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.By32KTZHTOkhuYIJqibVWgpISO9SzWofRB2NOFtesRrnlzqIuajEbJJOS4hD01EqsNJZwMtke4JNc7jlAyeo829QJbbMkvJ4Aa2H5H1vPAEJNTeNjYDWmb50cxeZ2EKqF2DE5rnkWtj1hboD3A0RGl7fpmomk0ONMlOJJIgBlZkM7-FTo5wgM3fZNKBTsHs588cGS9_cW5pbbIUWDzf4r-m4VWkLm5zD71zzhv-BpmFpuPo2ln1yN_d_Uir0Yq1zdlEOxE80hYe-ISoVIbm4pM37Seo53EFSarYZzgeEwJUaXliHTeOoiefudgkIqxC3yQhqRdCV9y4AsFa_Yx9-aQ

###

GET http://localhost:3000/categories HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InIyZ3dXbTVlTDdZc3lBQi1uWjl6RiJ9.eyJpc3MiOiJodHRwczovL2Vtb3VsdC5hdS5hdXRoMC5jb20vIiwic3ViIjoicjU2dEZ5S1hhYldES0h3d1BkY0h6QVpuZUUyalM1RzZAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vbG9nZ2VyLmVtb3VsdC5jb20iLCJpYXQiOjE1OTkxMDg0ODEsImV4cCI6MTU5OTE5NDg4MSwiYXpwIjoicjU2dEZ5S1hhYldES0h3d1BkY0h6QVpuZUUyalM1RzYiLCJzY29wZSI6ImxvZ2dlciByZWFkZXIgdXBkYXRlciBkZWxldGVyIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.By32KTZHTOkhuYIJqibVWgpISO9SzWofRB2NOFtesRrnlzqIuajEbJJOS4hD01EqsNJZwMtke4JNc7jlAyeo829QJbbMkvJ4Aa2H5H1vPAEJNTeNjYDWmb50cxeZ2EKqF2DE5rnkWtj1hboD3A0RGl7fpmomk0ONMlOJJIgBlZkM7-FTo5wgM3fZNKBTsHs588cGS9_cW5pbbIUWDzf4r-m4VWkLm5zD71zzhv-BpmFpuPo2ln1yN_d_Uir0Yq1zdlEOxE80hYe-ISoVIbm4pM37Seo53EFSarYZzgeEwJUaXliHTeOoiefudgkIqxC3yQhqRdCV9y4AsFa_Yx9-aQ

###

GET http://localhost:3000/creators HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InIyZ3dXbTVlTDdZc3lBQi1uWjl6RiJ9.eyJpc3MiOiJodHRwczovL2Vtb3VsdC5hdS5hdXRoMC5jb20vIiwic3ViIjoicjU2dEZ5S1hhYldES0h3d1BkY0h6QVpuZUUyalM1RzZAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vbG9nZ2VyLmVtb3VsdC5jb20iLCJpYXQiOjE1OTkxMDg0ODEsImV4cCI6MTU5OTE5NDg4MSwiYXpwIjoicjU2dEZ5S1hhYldES0h3d1BkY0h6QVpuZUUyalM1RzYiLCJzY29wZSI6ImxvZ2dlciByZWFkZXIgdXBkYXRlciBkZWxldGVyIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.By32KTZHTOkhuYIJqibVWgpISO9SzWofRB2NOFtesRrnlzqIuajEbJJOS4hD01EqsNJZwMtke4JNc7jlAyeo829QJbbMkvJ4Aa2H5H1vPAEJNTeNjYDWmb50cxeZ2EKqF2DE5rnkWtj1hboD3A0RGl7fpmomk0ONMlOJJIgBlZkM7-FTo5wgM3fZNKBTsHs588cGS9_cW5pbbIUWDzf4r-m4VWkLm5zD71zzhv-BpmFpuPo2ln1yN_d_Uir0Yq1zdlEOxE80hYe-ISoVIbm4pM37Seo53EFSarYZzgeEwJUaXliHTeOoiefudgkIqxC3yQhqRdCV9y4AsFa_Yx9-aQ

### 

POST http://localhost:3000/records HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InIyZ3dXbTVlTDdZc3lBQi1uWjl6RiJ9.eyJpc3MiOiJodHRwczovL2Vtb3VsdC5hdS5hdXRoMC5jb20vIiwic3ViIjoicjU2dEZ5S1hhYldES0h3d1BkY0h6QVpuZUUyalM1RzZAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vbG9nZ2VyLmVtb3VsdC5jb20iLCJpYXQiOjE1OTkxMDg0ODEsImV4cCI6MTU5OTE5NDg4MSwiYXpwIjoicjU2dEZ5S1hhYldES0h3d1BkY0h6QVpuZUUyalM1RzYiLCJzY29wZSI6ImxvZ2dlciByZWFkZXIgdXBkYXRlciBkZWxldGVyIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.By32KTZHTOkhuYIJqibVWgpISO9SzWofRB2NOFtesRrnlzqIuajEbJJOS4hD01EqsNJZwMtke4JNc7jlAyeo829QJbbMkvJ4Aa2H5H1vPAEJNTeNjYDWmb50cxeZ2EKqF2DE5rnkWtj1hboD3A0RGl7fpmomk0ONMlOJJIgBlZkM7-FTo5wgM3fZNKBTsHs588cGS9_cW5pbbIUWDzf4r-m4VWkLm5zD71zzhv-BpmFpuPo2ln1yN_d_Uir0Yq1zdlEOxE80hYe-ISoVIbm4pM37Seo53EFSarYZzgeEwJUaXliHTeOoiefudgkIqxC3yQhqRdCV9y4AsFa_Yx9-aQ

{
    "creator": "sample creator",
    "category": "sample cat",
    "key": "key",
    "value": "value",
    "timestamp": "2010-01-01T00:00:00.000Z"
}